### ISSUE TITLE
Work with Realsense D400

### ISSUE THREAD

**Issue by Alex-Beh** [tud-cor/spencer-yolo#2]
Hello, many I know does this package work with realsense D400 camera? From the main.cpp under yolo_pedestrian_detector directory, I saw the code is written with zed-camera library.

**Comment by bbrito** [comment]
In the beginning, we made it work with the D400 but the performance of the camera was not really good so we replace it with zed camera. I guess @PhiAbs can help you connect the D400

**Comment by Alex-Beh** [comment]
Yes I am happy if can get some help or hints on that.

I tried to use your idea and rewrite the code for realsense camera. The idea step by step is:
> 1. Use RGB Image for Yolo detection.
> 2. From the Yolo detection result, find the x_centre & y_centre. Then use the two value to find out the x,y & z distance in real world from the pointcloud2 message.
> 3. Fill the result into ROS message `<spencer_tracking_msgs/DetectedPersons.h>`.

I disable the original upper body detector and publish the yolo primary detection result into `"/spencer/perception_internal/detected_persons/rgbd_front_top/upper_body"`. The yellow icon is the result from yolo detection. The position seems wrong. Do I miss out any transformation or wrong idea to get the real world distance from pointcloud message?

I have uploaded my code to [link](https://github.com/Alex-Beh/realsense_yolo.git).

![Screenshot from 2020-07-20 16-58-17](https://user-images.githubusercontent.com/66585558/87919393-4fc84f00-caaa-11ea-80ab-0dd1a417dc3c.png)

Yolo Detection result:
![Screenshot from 2020-07-20 16-58-39](https://user-images.githubusercontent.com/66585558/87919562-8f8f3680-caaa-11ea-9b50-c0d683e32c4c.png)

**Comment by PhiAbs** [comment]
Judging from the images that you attached, it looks like one of the transformations is wrong. The ZED camera uses the following coordinate system: X-right, Y-down, Z-front. Could you check if you use the same coordinate system?

**Comment by Alex-Beh** [comment]
You are right. I fixed the issue by publish a static_tf_transform. From the detection_to_detection_fusion_pipeline.launch ([link](https://github.com/tud-amr/spencer-yolo/blob/4022b71e94176ef73dbad8a80d87538df2687eae/spencer_people_tracking/detection/spencer_detected_person_association/launch/detection_to_detection_fusion_pipeline.launch#L18)), I saw you have used the output either fuse from upper_body_detector or yolo_detection. May I know what is the reason not to fuse both detection result become one final_composite_topic?

**Comment by PhiAbs** [comment]
Great to hear that you could fix the issue!

For our setup, the upper_body_detector was very unreliable and it wouldn't have made sense to use its detection results. However, if the upper_body_detector gives reasonable results with your setup, it might be worth trying to fuse the detections with the ones from yolo_detection.

**Comment by jonathanleinola** [comment]
Hi! @Alex-Beh and @PhiAbs is there working branch with realsense camera and yolo detection already? I I'm trying to achieve the same thing with my detection + tracking pipeline and now it seems that the upper body detection is really the bottle-neck of the pipeline.

**Comment by PhiAbs** [comment]
Hi @jonathanleinola 
No, at least not from my side, sorry.

**Comment by kaushikbalasundar** [comment]
Hi @jonathanleinola, @PhiAbs and @Alex-Beh I am also working on the same problem, and would appreciate any leads on realsense + yolo version of this project. Thanks!
